### ISSUE TITLE
写这个用于哪个地方？

### ISSUE THREAD

**Issue by jianbinggouzi** [Hyq0719/marketing-api-java-sdks#15]
真的没别的意思，就是单纯的好奇。我在某个公司的项目也是对接这三个渠道，前前后后两年，最后项目还是流产了。因为有adsdesk、创Liang类似的这种产品

**Comment by Hyq0719** [comment]
用在某网文巨头的明星产品，主要用来采集实时的广告数据

**Comment by jianbinggouzi** [comment]
加油，兄弟
